services:
  elasticsearch:
    build:
      context: .
      dockerfile: etl/Dockerfile
    container_name: elasticsearch_engine
    expose:
      - "9200"
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      path.repo: /usr/share/elasticsearch/snapshot
    volumes:
      - ./etl/snapshot:/usr/share/elasticsearch/snapshot

  fastapi:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: fastapi_app
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - elasticsearch
      - redis
    entrypoint: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - fastapi

  redis:
    image: redis:latest
    container_name: redis_cache
    expose:
      - "6379"
